### ISSUE TITLE
[Feature] Allow only End Turn Button

### ISSUE THREAD

**Issue by ChasarooniZ** [TheDarkTongo/trinium-chat-buttons#2]
Option to allow you to set it so it shows the players the end turn button on their turn, and the GM the end turn button, but not the rest of the UI. 

My intention would be to use it in tandem with combat carousel or the like

**Comment by TheDarkTongo** [comment]
Good idea and should be very easy to implement. I'm going to push it today together with the new GM screen button :)

**Comment by TheDarkTongo** [comment]
Added in v1.4.0
