### ISSUE TITLE
[Feature] Have your turn automatically Pop up

### ISSUE THREAD

**Issue by ChasarooniZ** [TheDarkTongo/trinium-chat-buttons#3]
Have the Your Turn Button automatically expand out when it's the player's turn (as an option) If this was doable to have  this button show up for the DM as well when it's their character's turn too that'd be nice

**Comment by TheDarkTongo** [comment]
Could you explain in more detail? currently, the combat tracker should update automatically, but it needs to be toggled on via its dedicated button to do anything

**Comment by ChasarooniZ** [comment]
Uhh I guess what my request is, that I'd like to not have to manually toggle on the tracker?

My ideal use case is some thing like this:
- No Extra UI changes on screen
- When it is your character's turn the `End Your Turn Button` pops into existence
- When it isn't your turn it's gone
(goal is just to have a nice inline way to end your turn)

_if this doesn't fit the scope of the module feel free to shelve it_

**Comment by TheDarkTongo** [comment]
Oh, I get you now.

Auto opening the tracker on combat state change is actually a setting I wanted to add in but forgot, I will add it in soon.

As for the inline part, I was thinking about it but, with the current setup, that would leave the (currently limited) utility buttons next to the toggle in a very wide empty row, so the space taken would be exactly the same.

My idea was that once the utility buttons increase in number, the combat tracker toggle will be quite small and not feel like it's taking a whole line by itself

**Comment by TheDarkTongo** [comment]
Combat tracker now auto expands when you load in.
