### ISSUE TITLE
[Feature] GM Screen Journal Support

### ISSUE THREAD

**Issue by ChasarooniZ** [TheDarkTongo/trinium-chat-buttons#4]
IF this could support a journal entry it would allow usage of enrichers (like PF2e System roll Enrichers etc.)

**Comment by TheDarkTongo** [comment]
I also had this in mind, but I am not familiar with the journal classes.

I played with it for a few minutes when I started implementing the GM screen, but failed to make it work.

Tomorrow I add more gm screen tabs. Maybe in the future I can also add journal tabs if I can get them to work.

**Comment by ChasarooniZ** [comment]
That's very fair, same as well.

There was a GM screen Module that I think might provide some insight? 
[Code for them inserting journal entry](https://github.com/ElfFriend-DnD/foundryvtt-gmScreen/blob/main/src/module/classes/CompactJournalEntryDisplay.ts)

IMO it doesn't really need to be customizable or flexible (like if it just supported the option to input a journal entry UUID that would work perfectly, up to you though)

**Comment by TheDarkTongo** [comment]
I do know the GM Screen module and loved it! I used it all the time in v10 and used a half-working fork in v11. The Journal implementation has changed quite a bit since then so I'll have to mess with it.
And yes, the UUID way is the way I'm going to try to do it initially :)

**Comment by TheDarkTongo** [comment]
Okay, that was easy lol.
![image](https://github.com/user-attachments/assets/54dc8a91-da3e-48d0-a3db-2b923b2c97cf)
